import Link from "next/link";
import { CalendarCheck, ClipboardList, GraduationCap, Sparkles } from "lucide-react";
import { createServiceRoleClient } from "@/lib/supabase/server";
import { getInsightHistory, getStudentPerformanceSummary } from "@/lib/data/academics";
import { toInsightData } from "@/lib/ai/insight-mapper";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { StatTile } from "@/components/dashboard/stat-tile";
import { SubjectPerformanceChart } from "@/components/dashboard/subject-performance-chart";
import { InsightPanel } from "@/components/ai/insight-panel";
import { RiskHistoryTimeline } from "@/components/ai/risk-history-timeline";
import { EmptyState } from "@/components/shared/empty-state";

export const metadata = {
  title: "Live Demo",
  description: "See the AI Risk Center in action — no login required.",
};

// Public, read-only showcase of a real (seeded) at-risk student's AI Risk
// Center, so judges/visitors can see the platform's core feature in one
// click, without registering. Uses the service-role client deliberately —
// this is the one intentional exception to "students only see their own
// data," scoped to a single pre-selected demo account whose credentials are
// already published in the README and login page.
const DEMO_STUDENT_NAME = "Ethan Brooks";

export default async function DemoPage() {
  const supabase = createServiceRoleClient();

  const { data: student } = await supabase
    .from("profiles")
    .select("*")
    .eq("full_name", DEMO_STUDENT_NAME)
    .eq("role", "student")
    .maybeSingle();

  if (!student) {
    return (
      <div className="mx-auto max-w-2xl px-4 py-16">
        <EmptyState
          icon={Sparkles}
          title="Demo data not seeded yet"
          description="The live demo showcases a pre-seeded at-risk student. Once demo data exists, it'll appear here."
        />
      </div>
    );
  }

  const [summary, history, { data: latestInsight }, { data: latestPlan }] = await Promise.all([
    getStudentPerformanceSummary(supabase, student.id),
    getInsightHistory(supabase, student.id),
    supabase.from("ai_insights").select("*").eq("student_id", student.id).order("generated_at", { ascending: false }).limit(1).maybeSingle(),
    supabase.from("intervention_plans").select("*").eq("student_id", student.id).order("created_at", { ascending: false }).limit(1).maybeSingle(),
  ]);

  const initialInsight = latestInsight ? toInsightData(latestInsight) : null;

  return (
    <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8">
      <div className="ai-gradient-border mb-8 rounded-2xl p-5 text-center sm:p-6">
        <p className="flex items-center justify-center gap-1.5 text-sm font-semibold text-ai">
          <Sparkles className="size-4" /> Live demo — no login required
        </p>
        <p className="mx-auto mt-1 max-w-xl text-sm text-muted-foreground">
          This is a real, seeded student in EduPortal — attendance, assignments, and exam records were entered
          exactly as a teacher would, and everything below (risk level, evidence, recommendations, the 7-day
          intervention plan) was generated by the same code path a teacher or student sees after logging in.
        </p>
      </div>

      <div className="mb-6 flex items-center justify-between">
        <div>
          <p className="text-sm text-muted-foreground">Student</p>
          <h1 className="text-2xl font-bold">{student.full_name}</h1>
        </div>
        <Button asChild>
          <Link href="/login">Log in to explore the full platform</Link>
        </Button>
      </div>

      <div className="grid gap-4 sm:grid-cols-3">
        <StatTile
          icon={CalendarCheck}
          label="Attendance"
          value={summary.attendanceRate != null ? `${summary.attendanceRate}%` : "—"}
          hint={`${summary.attendancePresent}/${summary.attendanceTotal} sessions`}
        />
        <StatTile
          icon={ClipboardList}
          label="Assignment average"
          value={summary.overallAssignmentAvgPercent != null ? `${summary.overallAssignmentAvgPercent}%` : "—"}
        />
        <StatTile
          icon={GraduationCap}
          label="Exam average"
          value={summary.overallExamAvgPercent != null ? `${summary.overallExamAvgPercent}%` : "—"}
        />
      </div>

      <div className="mt-6 grid gap-6 lg:grid-cols-5">
        <Card className="lg:col-span-3">
          <CardContent>
            <h3 className="mb-1 font-semibold">Performance by subject</h3>
            <p className="mb-4 text-sm text-muted-foreground">Attendance, assignment, and exam averages per course.</p>
            <SubjectPerformanceChart subjects={summary.subjects} />
            <div className="mt-4 overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Subject</TableHead>
                    <TableHead className="text-right">Attendance</TableHead>
                    <TableHead className="text-right">Assignments</TableHead>
                    <TableHead className="text-right">Exams</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {summary.subjects.map((s) => (
                    <TableRow key={s.classId}>
                      <TableCell className="font-medium">{s.subject}</TableCell>
                      <TableCell className="text-right tabular-nums">{s.attendanceRate ?? "—"}%</TableCell>
                      <TableCell className="text-right tabular-nums">{s.assignmentAvgPercent ?? "—"}%</TableCell>
                      <TableCell className="text-right tabular-nums">{s.examAvgPercent ?? "—"}%</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>

        <div className="space-y-4 lg:col-span-2">
          <InsightPanel
            studentId={student.id}
            studentName={student.full_name}
            initialInsight={initialInsight}
            canRegenerate={false}
            initialPlan={latestPlan ?? null}
          />
          <RiskHistoryTimeline entries={history} />
        </div>
      </div>

      <div className="mt-10 rounded-2xl border bg-muted/30 p-6 text-center">
        <p className="font-semibold">Want to see the teacher and admin side?</p>
        <p className="mx-auto mt-1 max-w-lg text-sm text-muted-foreground">
          Log in with any of the demo accounts to mark attendance, grade assignments, generate a fresh AI insight, or
          view the system-wide risk dashboard.
        </p>
        <Button className="mt-4" asChild>
          <Link href="/login">Go to login</Link>
        </Button>
      </div>
    </div>
  );
}
